### ISSUE TITLE
onDestory crash 

### ISSUE THREAD

**Issue by creativetrendsapps** [eliseomartelli/SimpleCustomTabs#5]
USER_COMMENT=
ANDROID_VERSION=5.1
APP_VERSION_NAME=3.1.6
BRAND=motorola
PHONE_MODEL=XT1031
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: Unable to destroy activity {com.creativetrends.folio.app.key/com.creativtrendz.folio.activities.MainActivity}: java.lang.IllegalArgumentException: Service not registered: io.github.eliseomartelli.simplecustomtabs.CustomTabs$Warmer$1@3dfd399
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3791)
    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3809)
    at android.app.ActivityThread.access$1400(ActivityThread.java:155)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1371)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5343)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
Caused by: java.lang.IllegalArgumentException: Service not registered: io.github.eliseomartelli.simplecustomtabs.CustomTabs$Warmer$1@3dfd399
    at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1029)
    at android.app.ContextImpl.unbindService(ContextImpl.java:1947)
    at android.content.ContextWrapper.unbindService(ContextWrapper.java:551)
    at io.github.eliseomartelli.simplecustomtabs.CustomTabs$Warmer.unwarm(CustomTabs.java:351)
    at com.creativtrendz.folio.activities.MainActivity.onDestroy(MainActivity.java:1543)
    at android.app.Activity.performDestroy(Activity.java:6189)
    at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1164)
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3778)
    ... 10 more
java.lang.IllegalArgumentException: Service not registered: io.github.eliseomartelli.simplecustomtabs.CustomTabs$Warmer$1@3dfd399
    at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1029)
    at android.app.ContextImpl.unbindService(ContextImpl.java:1947)
    at android.content.ContextWrapper.unbindService(ContextWrapper.java:551)
    at io.github.eliseomartelli.simplecustomtabs.CustomTabs$Warmer.unwarm(CustomTabs.java:351)
    at com.creativtrendz.folio.activities.MainActivity.onDestroy(MainActivity.java:1543)
    at android.app.Activity.performDestroy(Activity.java:6189)
    at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1164)
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3778)
    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3809)
    at android.app.ActivityThread.access$1400(ActivityThread.java:155)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1371)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5343)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by eliseomartelli** [comment]
Hi!
Can you tell me the steps to reproduce it?

**Comment by creativetrendsapps** [comment]
Adding in Custom Tabs and warming them. In my onDestory I'm destroying my web view and unwarming the tabs. Unwarming causes the crash. Not unwarming the tabs runs fine.

so it's webView.onDestroy();
then the unwarm bit.

**Comment by creativetrendsapps** [comment]
I'll just try & catch the unwarm bit and ignore the exception.

**Comment by eliseomartelli** [comment]
It's strange... With the demo app under Android N I don't have any problems... 
Are you unwarming from a Fragment?

**Comment by eliseomartelli** [comment]
Can you try using this version of the library?

Unzip it and add the "library-sources.jar" as a file dependency and remove the previous one...

Let me know if it works!


[Archive.zip](https://github.com/eliseomartelli/SimpleCustomTabs/files/301820/Archive.zip)

**Comment by eliseomartelli** [comment]
Hi, 

Can you try using this version?

[simple-custom-tabs-1.4.1.aar.zip](https://github.com/eliseomartelli/SimpleCustomTabs/files/301837/simple-custom-tabs-1.4.1.aar.zip)

**Comment by creativetrendsapps** [comment]
I'll have to try it later. No, it's not from a fragment, it's from my main
activity.

**Comment by eliseomartelli** [comment]
Strange... try cloning this repo and compile the demo... it doesn't crash...

**Comment by creativetrendsapps** [comment]
Trust me, it does lol. On my Samsung device running Marshmallow it has no
crash at all. Running it on Lollipop and below result in a crash.

**Comment by theblixguy** [comment]
Same. Someone reported me the same issue today, 

java.lang.RuntimeException: Unable to destroy activity {com.suyashsrijan.forcedoze/com.suyashsrijan.forcedoze.MainActivity}: java.lang.IllegalArgumentException: Service not registered: io.github.eliseomartelli.simplecustomtabs.CustomTabs$Warmer$1@956fc77
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3930)
    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3948)
    at android.app.ActivityThread.access$1500(ActivityThread.java:154)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1445)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:224)
    at android.app.ActivityThread.main(ActivityThread.java:5526)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.IllegalArgumentException: Service not registered: io.github.eliseomartelli.simplecustomtabs.CustomTabs$Warmer$1@956fc77
    at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1048)
    at android.app.ContextImpl.unbindService(ContextImpl.java:1323)
    at android.content.ContextWrapper.unbindService(ContextWrapper.java:616)
    at io.github.eliseomartelli.simplecustomtabs.CustomTabs$Warmer.unwarm(CustomTabs.java:351)
    at com.suyashsrijan.forcedoze.MainActivity.onDestroy(MainActivity.java:211)
    at android.app.Activity.performDestroy(Activity.java:6441)
    at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1143)
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3917)
    ... 9 more

**Comment by eliseomartelli** [comment]
Hi!

Do you know on what version/device?

**Comment by eliseomartelli** [comment]
I think i've fixed the crash with version 1.4.3.
Can you please try and tell me if it's working as expected?

**Comment by creativetrendsapps** [comment]
To confirm version 1.4.3 fixes this issue.

**Comment by philippd1** [comment]
Really? Not for me...
Can you tell me if there's an error with my App or CustomTab? 
Build date: 2016-06-14 21:06:44 
Current date: 2016-06-15 21:08:09 
Device: LGE LG-H955 LG G Flex 2, 2GB RAM, Android 5.1.1

Stack trace:  
java.lang.RuntimeException: Unable to stop activity {de.ejherzo.konfiapp/de.ejherzo.konfiapp.MainActivity}: java.lang.IllegalArgumentException: Service not registered: io.github.eliseomartelli.simplecustomtabs.CustomTabs$Warmer$1@5fce549
	at android.app.ActivityThread.handleSleeping(ActivityThread.java:3614)
	at android.app.ActivityThread.access$2800(ActivityThread.java:162)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1524)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5431)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
Caused by: java.lang.IllegalArgumentException: Service not registered: io.github.eliseomartelli.simplecustomtabs.CustomTabs$Warmer$1@5fce549
	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1211)
	at android.app.ContextImpl.unbindService(ContextImpl.java:1943)
	at android.content.ContextWrapper.unbindService(ContextWrapper.java:551)
	at io.github.eliseomartelli.simplecustomtabs.CustomTabs$Warmer.unwarm(CustomTabs.java:351)
	at de.ejherzo.konfiapp.MainActivity.onStop(MainActivity.java:522)
	at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1277)
	at android.app.Activity.performStop(Activity.java:6204)
	at android.app.ActivityThread.handleSleeping(ActivityThread.java:3611)
	... 9 more
Mittwoch, 15 Juni 2016, 09:02Nachm. +02:00 von Jorell Rutledge  notifications@github.com :

**Comment by eliseomartelli** [comment]
Are you using the latest version of the library?

**Comment by philippdormann** [comment]
yes, 1.4.3

compile 'io.github.eliseomartelli:simple-custom-tabs:1.4.3'

**Comment by creativetrendsapps** [comment]
Are you warming the tabs after setContentView? Then super.onDestory();
warmer.unwarm();?

**Comment by philippdormann** [comment]
yes i am warming and unwarming as how you did it on the main page at "bare minimum"

**Comment by philippd1** [comment]
The situation is this:
I have an app with a NavigationDrawer. There are about 4 items you can click. If you click, it opens my method called openInCustomTab(final String UrlToOpen). so like this: 

else if (id == R.id.nav_meinkonto) {
                    openInCustomTab("http://website.com");
                }

It all works and I can close it as well. But after some time repeating the process (opening-closing about 2-5 times) my app isn't responding and after a while a black screen shows but nothing happens. Even the logcat doesn't show something...

**Comment by creativetrendsapps** [comment]
That's odd. it works perfectly for me now. this is how I'm running setContentView:

super.onCreate(savedInstanceState);
            FacebookSdk.sdkInitialize(this.getApplicationContext());
            callbackManager = CallbackManager.Factory.create();
            PreferenceManager.setDefaultValues(this, R.xml.navigation_preferences, false);
            PreferenceManager.setDefaultValues(this, R.xml.preferences, true);
            PreferenceManager.setDefaultValues(this, R.xml.customize_preferences, true);
            preferences = PreferenceManager.getDefaultSharedPreferences(this);
            trayPreferences = new TrayAppPreferences(getApplicationContext());
            setContentView(R.layout.activity_main);
            warmer = CustomTabs.with(getApplicationContext()).warm();
            Permiso.getInstance().setActivity(this);
            getWindow().setFlags(
                    WindowManager.LayoutParams.FLAG_HARDWARE_ACCELERATED,
                    WindowManager.LayoutParams.FLAG_HARDWARE_ACCELERATED);

and my onDestory method looks like this:

@Override
    public void onDestroy() {
        Log.i("MainActivity", "Destroying...");
        super.onDestroy();
        webView.removeAllViews();
        webView.destroy();
        warmer.unwarm();

```
}
```

everything get gets killed correctly without issue for me with 1.4.3. Are calling the onDestroy from the fragment or MainActivity?

**Comment by philippdormann** [comment]
onDestroy is called in MainActivity ;)
But it isn't actually called...
onPost resume is the only override method apart from oncreate and onstart

**Comment by philippd1** [comment]
package de.ejherzo.app;

/*******************************************************************
 * app von Philipp Dormann                                    *
 * *****************************************************************
 * Autor dieser App: Philipp Dormann                               *
 * Zweck dieser App: Konfirmanden der evangelischen Kirche         *
 * Herzogenaurach mehr für die Kirche                              *
 * und ihre Angebote begeistern                                    *
 * *****************************************************************
 * ©2016 app - Philipp Dormann                                *
 * *****************************************************************
 * 05.05.2016  | Philipp Dormann |                                 *
 * ------------|-----------------|---------------------------------*
 * 05/05/2016  | Philipp         |die App ist jetzt in der Alpha   *
 * |           |und im PlayStore verfügbar.                        *
 * |           |   (｡◕‿◕｡)(｡◕‿◕｡)(｡◕‿◕｡)(｡◕‿◕｡)                       *
 * |           |                                                   *
 ******************************************************************/

import android.content.Intent;
import android.content.SharedPreferences;
import android.net.ConnectivityManager;
import android.net.NetworkInfo;
import android.net.Uri;
import android.os.Bundle;
import android.preference.PreferenceManager;
import android.support.design.widget.FloatingActionButton;
import android.support.design.widget.NavigationView;
import android.support.multidex.MultiDex;
import android.support.v4.view.GravityCompat;
import android.support.v4.widget.DrawerLayout;
import android.support.v7.app.ActionBarDrawerToggle;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.util.Log;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.widget.Toast;

import com.edwardvanraak.materialbarcodescanner.MaterialBarcodeScanner;
import com.edwardvanraak.materialbarcodescanner.MaterialBarcodeScannerBuilder;
//import com.fatangare.logcatviewer.utils.LogcatViewer;
import com.github.javiersantos.appupdater.AppUpdater;
import com.google.android.gms.vision.barcode.Barcode;
import com.kobakei.ratethisapp.RateThisApp;
//import com.squareup.leakcanary.LeakCanary;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStreamWriter;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLEncoder;

import cat.ereza.customactivityoncrash.CustomActivityOnCrash;
import fragmente.Fragment_About;
import fragmente.Fragment_Help;
import fragmente.Fragment_Share;
import fragmente.Fragment_Texte;
import github.nisrulz.easydeviceinfo.EasyDeviceInfo;
import io.github.eliseomartelli.simplecustomtabs.CustomTabs;


public class MainActivity extends AppCompatActivity
        implements NavigationView.OnNavigationItemSelectedListener {

    private SharedPreferences prefs;
    private SharedPreferences.Editor prefseditor;
    private final String KEY_1 = "key1";
    private final String KEY_2 = "key2";

    private CustomTabs.Warmer warmer;
    private EasyDeviceInfo easyDeviceInfo;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        CustomActivityOnCrash.install(this);

        setContentView(R.layout.activity_main);

        //Warm up section
        warmer = CustomTabs.with(getApplicationContext()).warm();

        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//APP UPDATER
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        AppUpdater appUpdater = new AppUpdater(MainActivity.this);
        appUpdater
                .setDialogTitleWhenUpdateAvailable("Update verfügbar")
                .setDialogDescriptionWhenUpdateAvailable("Es ist ein neues Update für die app verfügbar.")
                .setDialogButtonUpdate("Updaten")
                .setDialogButtonDoNotShowAgain("Später")
                .start();

        easyDeviceInfo = new EasyDeviceInfo(MainActivity.this);
        prefs = MainActivity.this.getSharedPreferences("prefsdatei1", MODE_PRIVATE);
        prefseditor = prefs.edit();
        final String bname = prefs.getString(KEY_1, "Kein Benutzername gespeichert");

        MultiDex.install(MainActivity.this);

//        LeakCanary.install(getApplication());

//        sendAnalyticsToServer();

//        LogcatViewer.showLogcatLoggerView(MainActivity.this);

        FloatingActionButton fab = (FloatingActionButton) findViewById(R.id.fab);
        assert fab != null;
        fab.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                startScan();

            }
        });

        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                Toast.makeText(MainActivity.this, "Angemeldet als: " + bname, Toast.LENGTH_SHORT).show();
            }
        });

        DrawerLayout drawer = (DrawerLayout) findViewById(R.id.drawer_layout);
        ActionBarDrawerToggle toggle = new ActionBarDrawerToggle(
                this, drawer, toolbar, R.string.navigation_drawer_open, R.string.navigation_drawer_close);
        assert drawer != null;
        drawer.addDrawerListener(toggle);
        toggle.syncState();

        NavigationView navigationView = (NavigationView) findViewById(R.id.nav_view);
        assert navigationView != null;
        navigationView.setNavigationItemSelectedListener(this);

        android.app.FragmentManager fm = getFragmentManager();
        fm.beginTransaction().replace(R.id.content_frame, new Fragment_About()).commit();

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//NUR BEIM ERSTEN MAL DAS APP INTRO ZEIGEN
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        new Thread(new Runnable() {
            @Override
            public void run() {
                //  Initialize SharedPreferences
                SharedPreferences getPrefs = PreferenceManager
                        .getDefaultSharedPreferences(getBaseContext());

                //  Create a new boolean and preference and set it to true
                boolean isFirstStart = getPrefs.getBoolean("firstStart", true);

                //  If the activity has never started before...
                if (isFirstStart) {

                    //  Make a new preferences editor
                    SharedPreferences.Editor e = getPrefs.edit();

                    //  Edit preference to make it false because we don't want this to run again
                    e.putBoolean("firstStart", false);

                    //  Apply changes
                    e.apply();

                    //  Launch app intro
                    Intent i = new Intent(MainActivity.this, DefaultIntro.class);
                    startActivity(i);
                }
            }
        }).start();

    }

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//ENDE ON-CREATE
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//ZURÜCK TASTE-->DRAWER SCHLIESSEN
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    @Override
    public void onBackPressed() {
        DrawerLayout drawer = (DrawerLayout) findViewById(R.id.drawer_layout);
        assert drawer != null;
        if (drawer.isDrawerOpen(GravityCompat.START)) {
            drawer.closeDrawer(GravityCompat.START);
        } else {
            super.onBackPressed();
        }
    }

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//MENU (DREI PUNKTE)
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        final int id = item.getItemId();

        if (id == R.id.help_us) {
            startActivity(new Intent(MainActivity.this, HelpUs.class));
        } else if (id == R.id.about) {
            startActivity(new Intent(MainActivity.this, AboutNavigation.class));
        }

        //cases
        return super.onOptionsItemSelected(item);


    }

    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//NAVIGATION DRAWER ITEMS
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    @SuppressWarnings("StatementWithEmptyBody")
    @Override
    public boolean onNavigationItemSelected(MenuItem item) {
        // Handle navigation view item clicks here.
        final int id = item.getItemId();

        final android.app.FragmentManager fm = getFragmentManager();

        new Thread(new Runnable() {
            @Override
            public void run() {
                if (id == R.id.nav_level) {
//Level
                    openInCustomTab("http://app.de/level");

                } else if (id == R.id.nav_ranking) {
//Ranking
                    openInCustomTab("http://app.de/ranking");

                } else if (id == R.id.nav_newcode) {
//Code einlösen
                    startScan();

                } else if (id == R.id.nav_share) {
//Share App
                    fm.beginTransaction().replace(R.id.content_frame, new Fragment_Share()).commit();

                } else if (id == R.id.nav_texte) {
//Texte
                    fm.beginTransaction().replace(R.id.content_frame, new Fragment_Texte()).commit();

                } else if (id == R.id.nav_termine) {
//Termine
                    openInCustomTab("http://app.de/termine");

                } else if (id == R.id.nav_about) {
//About
                    fm.beginTransaction().replace(R.id.content_frame, new Fragment_About()).commit();

                } else if (id == R.id.nav_help) {
//Hilfe
                    fm.beginTransaction().replace(R.id.content_frame, new Fragment_Help()).commit();

                } else if (id == R.id.nav_meinkonto) {
//Mein Konto
                    openInCustomTab("http://app.de/mein_konto");
                }
            }
        }).start();


        DrawerLayout drawer = (DrawerLayout) findViewById(R.id.drawer_layout);
        assert drawer != null;
        drawer.closeDrawer(GravityCompat.START);
        return true;
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//In ChromeCustomTab öffnen
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    private void openInCustomTab(final String urlejherzo) {


        //Load section
        CustomTabs.with(getApplicationContext())
                .setStyle(new CustomTabs.Style(getApplicationContext())
                        .setShowTitle(true)
                        .setToolbarColor(R.color.toolbarColor))
                .setFallBackActivity(MainActivity.class)
                .openUrl(urlejherzo, this);

    }


    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//INTRO
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    public void startDefaultIntro(View v) {
        startActivity(new Intent(MainActivity.this, DefaultIntro.class));
    }

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//QR
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    private void startScan() {
        /**
         * Build a new MaterialBarcodeScanner
         */

        String Manufacturer = easyDeviceInfo.getManufacturer();

//        Toast.makeText(MainActivity.this, Manufacturer, Toast.LENGTH_LONG).show();

        if (Manufacturer.equals("samsung")) {

            Toast.makeText(MainActivity.this, "Für Samsung Geräte noch nicht verfügbar", Toast.LENGTH_LONG).show();
            startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse("http://app.de/einlosen")));

        } else {

            final MaterialBarcodeScanner materialBarcodeScanner = new MaterialBarcodeScannerBuilder()
                    .withActivity(MainActivity.this)
                    .withEnableAutoFocus(true)
                    .withBleepEnabled(true)
                    .withOnlyQRCodeScanning()
                    .withBackfacingCamera()
                    .withText("Code Scannen...")
                    .withResultListener(new MaterialBarcodeScanner.OnResultListener() {
                        @Override
                        public void onResult(Barcode barcode) {
                            final String code = barcode.rawValue;
                            //Benutzername aus den Prefs auslesen
                            final String bname = prefs.getString(KEY_1, "Kein Benutzername gespeichert");

                            //Einlösen
                            openInCustomTab("http://app.de/android_einlosen.php?code=" + code + "&bname=" + bname);

                        }
                    })
                    .build();
            materialBarcodeScanner.startScan();
        }
    }

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//BOSS ANALYTICS---ENTWICKLER: PHILIPP DORMANN
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    private void sendAnalyticsToServer() {
        //  Neuer Thread
        new Thread(new Runnable() {
            @Override
            public void run() {
                String language = easyDeviceInfo.getLanguage();
                String Manufacturer = easyDeviceInfo.getManufacturer();
                String Model = easyDeviceInfo.getModel();
                String OSCodename = easyDeviceInfo.getOSCodename();
                String OSVersion = easyDeviceInfo.getOSVersion();
                String BatteryLevel = Integer.toString(easyDeviceInfo.getBatteryPercentage());
                String Rooted = Boolean.toString(easyDeviceInfo.isDeviceRooted());
                String BuildVersionSDK = Integer.toString(easyDeviceInfo.getBuildVersionSDK());
                String Charging = Boolean.toString(easyDeviceInfo.isDeviceCharging());
                String IPAdress = easyDeviceInfo.getIPAddress(true);
//Bname
                prefs = getSharedPreferences("prefsdatei1", MODE_PRIVATE);
                prefseditor = prefs.edit();
                prefseditor.apply();
//Token
                SharedPreferences sharedPreferences = getSharedPreferences("prefsdatei_token", MODE_PRIVATE);

//Benutzername aus den Prefs auslesen
                String Savedbname = prefs.getString(KEY_1, "Kein Benutzername gespeichert");

//Token aus den Prefs auslesen
                String SavedToken = sharedPreferences.getString(KEY_2, "Kein Token gespeichert");

//An Server Senden
                if (internetAvailable()) {
                    sendToServer("Sprache: " + language + "| " + "Hersteller/ Modell: " + Manufacturer + " " + Model + "| " + "Android" + OSVersion + " " + OSCodename + "| " + "API: " + BuildVersionSDK + "| " + "Batterieladezustand: " + BatteryLevel + "| " + "Rooted: " + Rooted + "| " +
                            "Laedt auf: " + Charging + "| " + "IP Adresse " + IPAdress + "| " + "FCM Token: " + SavedToken + "| " + "Benutzername: " + Savedbname);

                } else {

                    runOnUiThread(new Runnable() {
                        @Override
                        public void run() {
                            Toast.makeText(MainActivity.this, "Internet ist nicht verfügbar.", Toast.LENGTH_SHORT).show();
                        }
                    });
                }

            }
        }).start();

    }


    // AN SERVER SENDEN
    private void sendToServer(final String text) {

        try {
            String textparam = "text1=" + URLEncoder.encode(text, "UTF-8");

            String scripturlstring = "http://website.com/receive_script_analytics_app.php";
            URL scripturl = new URL(scripturlstring);
            HttpURLConnection connection = (HttpURLConnection) scripturl.openConnection();
            connection.setDoOutput(true);
            connection.setRequestProperty("Content-Type", "application/x-www-form-urlencoded");
            connection.setFixedLengthStreamingMode(textparam.getBytes().length);

            OutputStreamWriter contentWriter = new OutputStreamWriter(connection.getOutputStream());
            contentWriter.write(textparam);
            contentWriter.flush();
            contentWriter.close();

            InputStream answerInputStream = connection.getInputStream();

            answerInputStream.close();
            connection.disconnect();

        } catch (IOException e) {
            e.printStackTrace();
        }

    }

    //Prüfen, ob Internet verfügbar
    private boolean internetAvailable() {
        ConnectivityManager connectivityManager = (ConnectivityManager) getSystemService(CONNECTIVITY_SERVICE);
        NetworkInfo networkInfo = connectivityManager.getActiveNetworkInfo();
        return networkInfo != null && networkInfo.isConnectedOrConnecting();
    }


    //onDestroy

    @Override
    protected void onDestroy() {
        super.onDestroy();

        warmer.unwarm();
        Log.d("MainActivity", "onDestroy");
    }


    @Override
    protected void onStart() {
        super.onStart();

        // Monitor launch times and interval from installation
        RateThisApp.onStart(this);
        // If the criteria is satisfied, "Rate this app" dialog will be shown

        RateThisApp.Config config = new RateThisApp.Config(7, 10);
// Custom title ,message and buttons names
        config.setTitle(R.string.title_rate_app_dialog);
        config.setMessage(R.string.message_rate_app_dialog);
        config.setYesButtonText(R.string.yes_rate_app_dialog);
        config.setNoButtonText(R.string.no_rate_app_dialog);
        config.setCancelButtonText(R.string.cancel_rate_app_dialog);
        RateThisApp.init(config);

        RateThisApp.showRateDialogIfNeeded(this);

        Log.d("MainActivtiy", "onStart");
    }

}


This is all of my MainActivity

**Comment by philippd1** [comment]
just ignore most of my comments...I'M from Germany sorry^^

**Comment by eliseomartelli** [comment]
Try to clean your project 👍

**Comment by philippdormann** [comment]
Yeah man just tried it before you wrote it. It works perfectly. Thanks for your Support Bro!
Mittwoch, 15 Juni 2016, 09:47Nachm. +02:00 von Eliseo Martelli  notifications@github.com :

**Comment by eliseomartelli** [comment]
Ok|
Hoping in no more problems like this one! 👍
