### ISSUE TITLE
Crash after opening→closing multiple times

### ISSUE THREAD

**Issue by philippdormann** [eliseomartelli/SimpleCustomTabs#6]
# Hey!
### I'm sorry, but It's me again.

The situation is this:
I have an app with a NavigationDrawer. There are about 4 items you can click. If you click, it opens my method called `openInCustomTab(final String urlejherzo).` so like this:
`else if (id == R.id.nav_meinkonto) {
    openInCustomTab("http://website.com");
}`

The method openInCustomTab looks like this:
`private void openInCustomTab(final String urlejherzo) {

```
    //Load section
    CustomTabs.with(getApplicationContext())
            .setStyle(new CustomTabs.Style(getApplicationContext())
                    .setShowTitle(true)
                    .setToolbarColor(R.color.toolbarColor))
            .setFallBackActivity(MainActivity.class)
            .openUrl(urlejherzo, this);

}`
```

It all works fine and I can close it as well. But after some time repeating the process (opening-closing most of the time after exactly 2 times) my app isn't responding and after a while a black screen shows and after long time an ANR appears. Even the logcat doesn't show something BUT this is the last log before black screen: `D/FirebaseApp: Notifying background state change listeners.`...

I don't know, but I spent 1 hour trying to obtain some stacktraces...But ADB doesn't give some results :/

So It is basically the same situation as yesterday, but I cannot provide stacktraces...Could you tell me how exactly I coukld do it?

Here's my MainActivity, by the way :) http://philippdo.bplaced.net/1/MainActivity.txt

**Comment by eliseomartelli** [comment]
Hi!

I'm testing the library like this:

https://youtu.be/1We4Ang5aa8

Don't know if it's my library fault the crash...

**Comment by philippdormann** [comment]
mh..it only crashes when closing second time...will look into your example
Do i have to add a class called FallBackActivity? or is it ok to just select my MainActivity?

**Comment by philippdormann** [comment]
Could that generate the error maybe?

**Comment by philippdormann** [comment]
mh...didn't change something.
Right now I got it like this:

> if (id == R.id.nav_level) {
> //Level
>                     CustomTabs.with(getApplicationContext())
>                             .setStyle(new CustomTabs.Style(getApplicationContext())
>                                     .setShowTitle(true)
>                                     .setCloseButton(android.R.drawable.button_onoff_indicator_off)
>                                     .setStartAnimation(android.R.anim.fade_in, android.R.anim.fade_out)
>                                     .setExitAnimation(android.R.anim.fade_in, android.R.anim.fade_out)
>                                     .setToolbarColor(R.color.colorPrimary))
>                             .setFallBackActivity(Activity_Fallback.class)
>                             .openUrl("http://websiteApp.de/level", MainActivity.this);

```
            } else if (id == R.id.nav_ranking) {
```


```
                CustomTabs.with(getApplicationContext())
                        .setStyle(new CustomTabs.Style(getApplicationContext())
                                .setShowTitle(true)
                                .setCloseButton(android.R.drawable.button_onoff_indicator_off)
                                .setStartAnimation(android.R.anim.fade_in, android.R.anim.fade_out)
                                .setExitAnimation(android.R.anim.fade_in, android.R.anim.fade_out)
                                .setToolbarColor(R.color.colorPrimary))
                        .setFallBackActivity(Activity_Fallback.class)
                        .openUrl("http://websiteApp.de/ranking", MainActivity.this);

            }
```

The error still appears..
after exactly 2 times...

**Comment by philippdormann** [comment]
So..I just noticed that the library itself has no problems.What I mean is that the FallbackAvtivity and everything works just fine
The problems is the CustomTab itself i think
Don't know if this actually helps :)

**Comment by eliseomartelli** [comment]
Try not setting a fallback activity

**Comment by philippdormann** [comment]
Tried it. Still crashes

**Comment by philippdormann** [comment]
Logcat tells me "I/art: Wrote stack traces to '/data/anr/traces.txt'"
So I went into C:\Users\Philipp\AppData\Local\Android\sdk\platform-tools\
Then I ran cmd and typed 

> adb pull /data/anr/traces.txt

CMD tells me:"remote object /data/anr/traces.txt does not exist"...

Any option how I could obtain stack traces?

**Comment by eliseomartelli** [comment]
Hi... Can you please try using the built-in memory monitor in Android Studio?

**Comment by philippdormann** [comment]
Yes. When I'm staying in a CustomTab for some time, It goes down from 82mb allocated to 78,38MB.
Then it stays constant at 78,38. Could also be that it is my app going down with memory after a while..
2nd time customtab crashes and black screen

**Comment by philippdormann** [comment]
ok yeah...so it is definetly the custom tab ;)
app itself has constant memory. when i open customtab it has an (i think) significant loss of memory ;)

**Comment by philippdormann** [comment]
do i have to unbind any resources, drawables or firebase services from MainActivity?

**Comment by philippdormann** [comment]
OK **good news** !
Fixed some of my code, checked everything I did before, analyzed stack traces, cleaned project.
**BUT** the library still seems to produce memory leak I think..
Anyways I fixed it for me

**Comment by philippdormann** [comment]
I'm sorry, but error still occurs...
Any solution so far?

**Comment by philippdormann** [comment]
# Hello?

@eliseomartelli

**Comment by eliseomartelli** [comment]
Hi. 

Can you please email me here? 
martely98+work@gmail.com

**Comment by philippdormann** [comment]
OK. so I just had to work on RAM management in my app.
Thank you for the advices
Greetings from Germany!
Philipp
